Repository hctnm1/Hacky-Py, pull requests merged in 2022-10, with the labels that each got.

#1 Create Calculator.py
  Calculator.py
Labels: hacktoberfest, hacktoberfest-accepted

#3 Create Color_Game
  codes/Color_Game
Labels: hacktoberfest, hacktoberfest-accepted

#6 roman-to-numeral.py
  codes/roman-to-numeral.py
Labels: hacktoberfest, hacktoberfest-accepted

#8 Created a simple program to find the total of a Fibonacci sequence re…
  codes/fibonacci.py
Labels: hacktoberfest, hacktoberfest-accepted

#9 Create BMICalc.py
  codes/BMICalc.py
Labels: hacktoberfest, hacktoberfest-accepted

#10 Create Multiplication_table.py
  codes/Multiplication_table.py
Labels: hacktoberfest-accepted

#11 Add `lock_files.py`.
  codes/lock_files.py
Labels: hacktoberfest-accepted

#12 Added Password Generator
  codes/Random_Password_Gen.py
Labels: hacktoberfest-accepted

#13 pattern
  codes/pattern.py
Labels: hacktoberfest-accepted

#14 Add `tic-tac-toe.py`.
  codes/tic-tac-toe.py
Labels: hacktoberfest-accepted

#25 Create seatarrangement.py
  codes/seatarrangement.py
Labels: good first issue, hacktoberfest-accepted

#28 Create pathSum.py
  codes/pathSum.py
Labels: good first issue, hacktoberfest-accepted

#29 #real yagami 2 Create Dijkstra.py
  codes/Dijkstra.py
Labels: good first issue, hacktoberfest-accepted

#30 Wish birthday using python
  codes/birthday.py
Labels: good first issue, hacktoberfest-accepted

#31 #real yagami 3 Create pigenhole.py
  codes/pigenhole.py
Labels: good first issue, hacktoberfest-accepted

#33 #real yagami 5 Create bucket_sort.java
  codes/bucket_sort.java
Labels: good first issue, hacktoberfest-accepted

#34 real yagami 6 Create push_zero_to_end.py
  codes/push_zero_to_end.py
Labels: good first issue, hacktoberfest-accepted

#35 Create Snake_Game.py
  codes/Snake_Game.py
Labels: good first issue, hacktoberfest-accepted

#36 code for image compression added
  codes/imageCompression.py
Labels: good first issue, hacktoberfest-accepted

#37 Create calculator-recipet.py
  codes/calculator-recipet.py
Labels: good first issue, hacktoberfest-accepted

#38 Create alarm.py
  codes/alarm.py
Labels: good first issue, hacktoberfest-accepted

#39 Create anamolydetection.py
  codes/anamolydetection.py
Labels: good first issue, hacktoberfest-accepted

#40 Create date_cleaner.py
  codes/date_cleaner.py
Labels: good first issue, hacktoberfest-accepted

#41 Create insertionsort.py
  codes/insertionsort.py
Labels: good first issue, hacktoberfest-accepted

#42 Create kruskalalgo.py
  codes/kruskalalgo.py
Labels: good first issue, hacktoberfest-accepted

#43 Create pwd_gen.py
  codes/pwd_gen.py
Labels: good first issue, hacktoberfest-accepted

#44 Create pwd_validator.py
  codes/pwd_validator.py
Labels: good first issue, hacktoberfest-accepted

#45 Create mergeSortAlgo.py
  codes/mergeSortAlgo.py
Labels: good first issue, hacktoberfest-accepted

#46 Create rabin_karp.py
  codes/rabin_karp.py
Labels: good first issue, hacktoberfest-accepted

#47 Create watch.py
  codes/watch.py
Labels: good first issue, hacktoberfest-accepted

#48 Median of two array
  codes/median.py
Labels: good first issue, hacktoberfest-accepted

#86 ci(Mergify): configuration update
  .mergify.yml
Labels: good first issue, hacktoberfest-accepted
